<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ColorfulLedKeyboard.Tests" />
    <InternalsVisibleTo Include="ColorfulLedKeyboard.Tray" />
    <InternalsVisibleTo Include="ColorfulLedKeyboard.Tray.Wpf" />
  </ItemGroup>

</Project>
